{% set version = "1.19.2" %}

package:
  name: tableschema
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tableschema/tableschema-{{ version }}.tar.gz
  sha256: 65c65b92331d2200c87de9f69705bfe5d3d5a25be2c71805e2e5affa2ced0e5d

build:
  number: 0
  noarch: python
  entry_points:
    - tableschema = tableschema.__main__:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cached-property >=1.5
    - click >=3.3
    - isodate >=0.5.4
    - jsonschema >=2.5
    - python-dateutil >=2.4
    - requests >=2.5
    - rfc3986 >=1.1.0
    - six >=1.9
    - tabulator >=1.29
    - unicodecsv >=0.14

test:
  imports:
    - tableschema
    - tableschema.constraints
    - tableschema.plugins
    - tableschema.types
  requires:
    - pylama
    - tox
    - pip
  commands:
    - pip check
    - tableschema --help

about:
  home: https://github.com/frictionlessdata/tableschema-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A utility library for working with Table Schema in Python

extra:
  recipe-maintainers:
    - ocefpaf
    - roll
