{% set version = "1.5.3" %}

package:
  name: tableschema
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tableschema/tableschema-{{ version }}.tar.gz
  sha256: 1e5000a8aad6a52b54f3c84804ccaabfda6d1c28759a7c5d0ad45148959467ab

build:
  number: 0
  noarch: python
  entry_points:
    - tableschema = tableschema.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.9,<2.0
    - click >=3.3,<8.0
    - requests >=2.5,<3.0
    - python-dateutil >=2.4,<3.0
    - jsonschema >=2.5,<3.0
    - unicodecsv >=0.14,<2.0
    - isodate >=0.5.4,<2.0
    - rfc3986 >=1.1.0,<2.0
    - tabulator >=1.3,<2.0

test:
  imports:
    - tableschema
    - tableschema.constraints
    - tableschema.plugins
    - tableschema.types
  commands:
    - tableschema --help
  requires:
    - pylama
    - tox

about:
  home: https://github.com/frictionlessdata/tableschema-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A utility library for working with Table Schema in Python

extra:
  recipe-maintainers:
    - ocefpaf
