travis:
  secure:
    BINSTAR_TOKEN: Q1EMCrNH7o6X5YgQu8RI4XjfEVeiriZd+1OAF/4GIfPNWzXORuerfI0cDKLVNSRoTCRmN/Q4EQtP5D4bK/VmePzvh74QxRDh/kEpa4EQcMKxfLV7tiL0NTciCu7mkzd3037p81zfsEH2tybdcQ4Nk9PrgcLO79/zQlVazEwAR2zHWCUz69rU5yLU2DSGH94qdjffeCh5a9uI0D3eBbn/sTgXHqOjbJWr1wRQ+1kWyTX4TMYEq2iOuHc75eZldFIpoRAfHs+7fRo8SoFaOExU483EKSPhItPMw01BT69/8FBh+E20i1MZJVvenQhzyoBPix5+SOAYnu+5fHktqOGmZjjEunKhUhfE+2MvMtoxvyzJQ91mK/xvfZJVGQLYIjCI8hJrNy88XKaXk9O75w/d52m002XVhjZXZvGOxTu5cB7P5tyRO+otKLfqt7CmNGj4cnjyy96Q6v70Z6ZaWXRSfmkPrrVx4RcagZOYHWm/toAO0fy3uvwwng8/7EFu04XRUsF3gkKaOh8oysmDbNTINi4PyhPkEDdb5gLYfu9Z3b1dBI10+iF5ncjG7rV30vM08/ojxLHB1vu6N1x45sPOjv1U51LPZVwV6cb7oGyjPa39U8Vjv0T2Xkn8X+NUsbK8Yz4NxkfhtzoK7qkp6ZthhB8JmVKCgw5GRoVEEOP/tAo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
