travis:
  secure:
    BINSTAR_TOKEN: McaoFTMyIhk1nXb1KNC5b0kS3W1SAemLuLhubqFYAa/SPl/Dwkea31CS/JfktMq7kyKtJRV3h8Ux7qstrURLigN55BovoYCWKAywK4wW6fpkuyHrPpZ1YSIc49LF2VC7IqEGOiqoP/Lb06dcUzTIhUIwGlfHH+a/XjFbc8wGz6U3XrN1N0TqI6NdpFi563zO6Z1ByvKYWoBCFAWk1Gf+kbD60lArEN9fcO9txQWthLT8sQdce3OI+MN3tKIp8lfwuYJd98l52aoO7Iu2G2+SLz+qwrAMBcdwxKjCpD/81D058WsEZs/QsxSxyStdJC5Ajn9dO4lV4JHalWroVq8TVsORfsSH63nq2TnZsx319Pb7sVt5oktqB6Ed25EgGCe/1e9zdd0lT6IMcreQ6Vz4uu1mA4prN4g9qcztiePdD3yuh7Wjcbq9CJ7TLT4OmXoLUR7dNCLehM0doY6cK9m5ykEwcq6mxgmItfwFBGkGKA1vDXeQiQ+bTF5OpP2ZoJyPuV/CdqqnweYmnER0SNSSNdfZ35ggq11/ppcRKfcjom6b/GwFTuRfzd4aXpLQPhlD2vd24ETSldryEPYpKGnJt9gF50HzaADwXINKU4nH5tYXbVibYPvh1GHWKIoBYiLPlav9H4XXlFJcpa6GjhvyoM0T2kNl32gGtXu2bK/vJjY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
